ALTER TABLE orders
MODIFY status ENUM('PENDING', 'PROCESSING', 'CONFIRMED', 'FAILED')
NOT NULL DEFAULT 'PENDING';


UPDATE orders
SET status = 'PROCESSING'
WHERE status = 'PENDING';

ALTER TABLE orders
MODIFY COLUMN status ENUM('PROCESSING', 'CONFIRMED', 'FAILED')
NOT NULL DEFAULT 'PROCESSING';