server:
  port: 8084

spring:
  application:
    name: order

  datasource:
    url: ${ORDER_DB_URL:jdbc:mysql://localhost:3309/orderdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${ORDER_DB_USER:order}
    password: ${ORDER_DB_PASS:orderpw}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-inventory-result-g1
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.flashSale.order.events.InventoryResultEvent
        spring.json.use.type.headers: false
    listener:
      ack-mode: manual


inventory:
  base-url: http://localhost:8083
  timeout-ms: 1500

